T8=stop; if wait_ready && drained && metrics itest-reboot-q2 pre-reboot && $REC snap --prefix $P/itest-reboot-q2 --label pre-reboot --seed 42 && ssh egw-tcg cat /proc/sys/kernel/random/boot_id > $P/itest-reboot-q2.boot_id.pre && [[ $(cat $P/itest-reboot-q2.boot_id.pre) =~ ^[0-9a-f-]{36}$ ]] && ssh egw-tcg 'docker ps -q --no-trunc --filter status=running | sort' > $P/itest-reboot-q2.containers.pre && [ -s $P/itest-reboot-q2.containers.pre ] && [ "$(wc -l < $P/itest-reboot-q2.containers.pre)" = 6 ] && ssh egw-tcg 'ls -1 /opt/egw/deployment/data/events | sort' > $P/itest-reboot-q2.events.pre && grep -q . $P/itest-reboot-q2.events.pre && ssh egw-tcg 'findmnt -no SOURCE /var/lib/docker' > $P/itest-reboot-q2.docker-mount.pre && grep -q . $P/itest-reboot-q2.docker-mount.pre; then ssh egw-tcg 'sudo journalctl --list-boots | tail -n 2; ls /opt/egw/deployment/data/events; sudo systemctl reboot'; T8=rebooting; echo "reboot command sent (status not tested) $(date -u +%FT%TZ): boot id $(cat $P/itest-reboot-q2.boot_id.pre), $(wc -l < $P/itest-reboot-q2.containers.pre) running container ids, $(wc -l < $P/itest-reboot-q2.events.pre) event directory names and /var/lib/docker on $(cat $P/itest-reboot-q2.docker-mount.pre) saved"; else stop "test 8: no pre-reboot /metrics reading or twin snapshot, no boot id of the kernel file's form (36 characters of 0-9, a-f and '-'), not six running containers (docker ps -q --no-trunc --filter status=running), no event directory listed under /opt/egw/deployment/data/events, or no mount source for /var/lib/docker (findmnt -no SOURCE: the data disk of 3.2) - the guest was NOT rebooted"; fi     # all three seed-42 twins, whatever earlier tests left in them; the /metrics reading keeps the pre-reboot started_at (line e), the container ids the set that must come back on its own (line c: the same read, so a container Docker lists as Restarting is in neither), and the sorted event directory names and the mount source of /var/lib/docker what line c judges intact after the reboot (both files must hold a line); the ssh status of the reboot is not tested: the connection drops with the reboot
# The launcher of 3.3 (scripts/run-qemu-integrated.sh) runs QEMU WITHOUT -no-reboot (observed on 2026-10-03, S2: the guest
# rebooted INSIDE THE SAME QEMU PROCESS - boot id d22195a1... -> 76471e31..., the previous boot ended 14:25:44Z, the new one
# began 14:26:15Z, the six containers' start times reached 14:26:46Z with nothing started by hand, their health read later).
# Nothing is re-launched here: the next line waits for the same guest to answer with a different boot id. A QEMU process
# that exits instead (another launcher, -no-reboot on its command line) makes that line STOP; a re-launch as in 3.3 with
# the same data disk is then an operator decision, recorded in the session record, never automatic. T8 carries this test's
# state between its lines - rebooting (a), rebooted (b), returned (c), reconnected (d), ok (e) - and every line advances it
# only on success: after a STOP the lines below refuse, and so do they in a new shell (T8 empty). A driver that runs these
# lines in separate shells sets T8 to the value the previous line left, and only when that line printed no STOP:.
