R=itest-mongo-fault-01-q1; SVC=mongodb
DC="cd /opt/egw/deployment && docker compose --env-file .env --env-file images.lock.env"
svc_state() { local s; s=$(ssh egw-tcg "c=\$($DC ps -aq $SVC) && [ -n \"\$c\" ] && docker inspect --format '{{.State.Status}}' \$c" 2>/dev/null | tail -n 1); echo "${s:-unknown}"; }
fault_recover() { local rc s0 s; s0=$(svc_state); ssh egw-tcg "$DC start $SVC"; rc=$?; s=$(svc_state); echo "start exit=$rc state_after_start=$s state_before_start=$s0 $(date -u +%FT%TZ)"; if [ "$rc" = 0 ] && [ "$s" = running ] && [ "$s0" = exited ]; then echo "RECOVERY SHOWN: $SVC is 'running' after start (it was 'exited' before the start)"; elif [ "$rc" = 0 ] && [ "$s" = running ]; then echo "NO RECOVERY TO SHOW: $SVC is 'running' after start, but it was '$s0' before the start - a return from 'exited' was not observed"; return 1; else echo "STOP: the recovery of $SVC is NOT shown (start exit=$rc, state '$s') - start it by hand before anything else: ssh egw-tcg \"$DC start $SVC\""; return 1; fi; }
fault() {
        local rc s0 s1 bad=0
        trap 'echo "STOP: the fault job was interrupted - the recovery is attempted now"; fault_recover; exit 1' INT TERM HUP
        sleep 90 & wait $!
        if pgrep -f "egw_simulator run .*--run-id $R( |\$)" >/dev/null; then
          s0=$(svc_state); ssh egw-tcg "$DC stop $SVC"; rc=$?; s1=$(svc_state)
          echo "stop exit=$rc state_before=$s0 state_after_stop=$s1 $(date -u +%FT%TZ)"
          if [ "$rc" = 0 ] && [ "$s0" = running ] && [ "$s1" = exited ]; then echo "INTERRUPTION SHOWN: $SVC went from 'running' to 'exited'"; else echo "STOP: the interruption of $SVC is NOT shown (stop exit=$rc, state '$s0' -> '$s1') - this run is not a fault test"; bad=1; fi
          sleep 45 & wait $!
        else
          echo "STOP: no simulator process for $R at +90 s - the fault was NOT injected"; bad=1
        fi
        fault_recover || bad=1
        return $bad
      }
readyp() { while :; do printf '%s %s\n' "$(date -u +%FT%TZ)" "$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 $CTRL/ready)"; sleep 2; done; }
T7=stop; if pre $R 42 && T0_7=$(events_start $R); then fault > $P/$R.fault.txt 2>&1 < /dev/null & FAULTP=$!; readyp > $P/$R.ready.txt < /dev/null & READYP=$!; sim_post $R --seed 42 --scenario nominal --duration 300; SP=$?; wait $FAULTP; FW=$?; kill $READYP; RK=$?; cat $P/$R.fault.txt; sut_log controller $R "$T0_7"; LC=$?; sut_log broker $R "$T0_7"; LB=$?; events_stop $R "$T0_7" die,stop,start egw-$SVC-1; EV=$?; if [ "$SP" = 0 ] && [ "$FW" = 0 ] && grep -q '^INTERRUPTION SHOWN' $P/$R.fault.txt && grep -q '^RECOVERY SHOWN' $P/$R.fault.txt && ! grep -q '^STOP' $P/$R.fault.txt && [ "$RK" = 0 ] && [ -f $P/$R.ready.txt ] && [ -s $P/$R.ready.txt ]; then if [ "$EV" = 0 ] && [ "$LC" = 0 ] && [ "$LB" = 0 ]; then T7=0; else T7="incomplete:events_stop=$EV,controller_log=$LC,broker_log=$LB"; stop "test 7: the interruption and the recovery are shown (the SHOWN lines above; $R.fault.txt and $R.ready.txt kept), but this sub-check's instrumentation is INCOMPLETE (events_stop exit=$EV: 1 = the capture not shown complete, 3 = the capture complete and the recorder's cleanup failed; controller log read exit=$LC, broker log read exit=$LB) - not accepted and not evaluated"; fi; else T7="failed:sim_post=$SP,fault_job=$FW,readyp_kill=$RK,events_stop=$EV,controller_log=$LC,broker_log=$LB"; stop "test 7: NOT accepted (sim_post exit=$SP, fault job exit=$FW, kill of the /ready poller exit=$RK; beside them, this sub-check's instrumentation: events_stop exit=$EV, controller log read exit=$LC, broker log read exit=$LB; a fault job exit other than 0, a STOP line above, a missing INTERRUPTION SHOWN or RECOVERY SHOWN line, a /ready poller that was no longer running at the end (kill exit other than 0: $R.ready.txt does not cover the run), or an empty $R.fault.txt/$R.ready.txt) - check that $SVC is running: ssh egw-tcg \"$DC ps $SVC\""; fi; else stop "test 7: precondition failed - NO fault was injected and nothing was published"; fi
[ "$T7" = 0 ] && python3 -c "import json,collections;ev=[json.loads(l) for l in open('$HOME/egw-tcg/itest/$R/events.jsonl')];print(collections.Counter((e['outcome'],e.get('attempts')) for e in ev)); print([e['error'] for e in ev if e['outcome']=='failed'][:3])" || stop "test 7: not evaluated (T7='$T7': only 0 = run complete AND interruption shown AND recovery shown)"
[ "$T7" != stop ] && [ "$LC" = 0 ] && [ -s $P/$R.sut/controller.log ] && [ -s $P/$R.twins.after.json ] && { $REC delta $P/$R --controller-log $P/$R.sut/controller.log; case $? in 0|4) true;; *) false;; esac; } || stop "test 7: the optional N1 report was NOT produced (the test line left T7='$T7' - 'stop' when its precondition failed or it was interrupted, and the files of $R may then be an earlier execution's -, controller log read exit='$LC', $P/$R.sut/controller.log or $P/$R.twins.after.json missing or empty, or delta could not be carried out) - it is read-only: finish's delta and T7='$T7' stand"     # optional and read-only (decision 2 of 2026-09-30), and only after a test line that started its run (T7 not 'stop': LC alone may be left in this shell by an earlier sub-check, and a refused precondition leaves the run id's earlier files as they were): delta again on the same files, with the sub-check's controller log read by the test line as the A3 source of its N1 report; 0 and 4 are both results (an identity it names n1_applied_unconfirmed already made finish's delta a MISMATCH, so T7 is then 'failed:'); it writes nothing, changes no status and decides nothing; an itest run has no restart record, so no controller death is a source here, and the twin evidence is the 'after' /metrics reading that finish took after 'drained'; UNVERIFIED: on a real controller log (Appendix B, item 24)
